[assets.images]
player_ship_blue = "space_shooter/Player/playerShip1_blue.png"
player_ship_green = "space_shooter/Player/playerShip1_green.png"
player_ship_orange = "space_shooter/Player/playerShip1_orange.png"
player_ship_red = "space_shooter/Player/playerShip1_red.png"
laser_red = "space_shooter/Lasers/laserRed07.png"
meteor_brown_lg_01 = "space_shooter/Meteors/meteorBrown_big1.png"
meteor_brown_lg_02 = "space_shooter/Meteors/meteorBrown_big2.png"
meteor_brown_lg_03 = "space_shooter/Meteors/meteorBrown_big3.png"
meteor_brown_lg_04 = "space_shooter/Meteors/meteorBrown_big4.png"
meteor_brown_md_01 = "space_shooter/Meteors/meteorBrown_med1.png"
meteor_brown_md_02 = "space_shooter/Meteors/meteorBrown_med3.png"
meteor_brown_sm_01 = "space_shooter/Meteors/meteorBrown_small1.png"
meteor_brown_sm_02 = "space_shooter/Meteors/meteorBrown_small2.png"
meteor_brown_tn_01 = "space_shooter/Meteors/meteorBrown_tiny1.png"
meteor_brown_tn_02 = "space_shooter/Meteors/meteorBrown_tiny2.png"
meteor_grey_lg_01 = "space_shooter/Meteors/meteorGrey_big1.png"
meteor_grey_lg_02 = "space_shooter/Meteors/meteorGrey_big2.png"
meteor_grey_lg_03 = "space_shooter/Meteors/meteorGrey_big3.png"
meteor_grey_lg_04 = "space_shooter/Meteors/meteorGrey_big4.png"
meteor_grey_md_01 = "space_shooter/Meteors/meteorGrey_med1.png"
meteor_grey_md_02 = "space_shooter/Meteors/meteorGrey_med2.png"
meteor_grey_sm_01 = "space_shooter/Meteors/meteorGrey_small1.png"
meteor_grey_sm_02 = "space_shooter/Meteors/meteorGrey_small2.png"
meteor_grey_tn_01 = "space_shooter/Meteors/meteorGrey_tiny1.png"
meteor_grey_tn_02 = "space_shooter/Meteors/meteorGrey_tiny2.png"

[assets.audio]
laser = "scifi_sounds/laserRetro_001.ogg"
explosion = "scifi_sounds/explosionCrunch_000.ogg"
thruster = "scifi_sounds/thrusterFire_000.ogg"

[player.ship]
thrust_factor = 800.0
turn_factor = 40.0
velocity_damping = 0.8
rotation_rate_damping = 8.0
sprite_id = "player_ship_orange"
collision_radius = 16
shoot_cooldown = 0.5

[meteors.variants.brown]

[meteors.variants.brown.Large]
scale = 2.5
speed = 32
sprites = [
	"meteor_brown_lg_01",
	"meteor_brown_lg_02",
	"meteor_brown_lg_03",
	"meteor_brown_lg_04",
]
collision_radius = 32

[meteors.variants.brown.Medium]
scale = 3
speed = 64
sprites = ["meteor_brown_md_01", "meteor_brown_md_02"]
collision_radius = 24

[meteors.variants.brown.Small]
scale = 4
speed = 128
sprites = ["meteor_brown_sm_01", "meteor_brown_sm_02"]
collision_radius = 16

[meteors.variants.brown.Tiny]
scale = 4
speed = 256
sprites = ["meteor_brown_tn_01", "meteor_brown_tn_02"]
collision_radius = 4

[meteors.variants.grey]

[meteors.variants.grey.Large]
scale = 3
speed = 32
sprites = [
	"meteor_grey_lg_01",
	"meteor_grey_lg_02",
	"meteor_grey_lg_03",
	"meteor_grey_lg_04",
]
collision_radius = 48

[meteors.variants.grey.Medium]
scale = 3
speed = 64
sprites = ["meteor_grey_md_01", "meteor_grey_md_02"]
collision_radius = 24

[meteors.variants.grey.Small]
scale = 4
speed = 128
sprites = ["meteor_grey_sm_01", "meteor_grey_sm_02"]
collision_radius = 16

[meteors.variants.grey.Tiny]
scale = 4
speed = 256
sprites = ["meteor_grey_tn_01", "meteor_grey_tn_02"]
collision_radius = 4

[projectile]
sprite_id = "laser_red"
speed = 1024
collision_radius = 4
scale = 2.5
lifetime = 1

[viewport]
title = "Stroids"
resolution = [800, 600]
# Tells wasm to resize the window according to the available canvas
fit_canvas_to_parent = false
# Tells wasm not to override default event handling, like F5, Ctrl+R etc.
prevent_default_event_handling = false
background_color = "#080811"
camera_scale = 3.0
bounding_margin = 100
