[assets.images]
player_ship = "space_shooter/Player/playerShip1_orange.png"

[player.ship]
thrust_factor = 350.0
turn_factor = 7.0
velocity_damping = 0.3
rotation_rate_damping = 0.7
sprite_id = "player_ship"


[viewport]
title = "Stroids"
resolution = [800, 600]
# Tells wasm to resize the window according to the available canvas
fit_canvas_to_parent = false
# Tells wasm not to override default event handling, like F5, Ctrl+R etc.
prevent_default_event_handling = false
background_color = "#111122"
camera_scale = 3.0
