[assets.images]
player_ship_blue = "space_shooter/Player/playerShip1_blue.png"
player_ship_green = "space_shooter/Player/playerShip1_green.png"
player_ship_orange = "space_shooter/Player/playerShip1_orange.png"
player_ship_red = "space_shooter/Player/playerShip1_red.png"

[player.ship]
thrust_factor = 800.0
turn_factor = 40.0
velocity_damping = 0.8
rotation_rate_damping = 8.0
sprite_id = "player_ship_orange"


[viewport]
title = "Stroids"
resolution = [800, 600]
# Tells wasm to resize the window according to the available canvas
fit_canvas_to_parent = false
# Tells wasm not to override default event handling, like F5, Ctrl+R etc.
prevent_default_event_handling = false
background_color = "#111122"
camera_scale = 3.0
