[assets.images]
player_ship_blue = "space_shooter/Player/playerShip1_blue.png"
player_ship_green = "space_shooter/Player/playerShip1_green.png"
player_ship_orange = "space_shooter/Player/playerShip1_orange.png"
player_ship_red = "space_shooter/Player/playerShip1_red.png"
laser_red = "space_shooter/Lasers/laserRed07.png"
meteor_brown_lg_01 = "space_shooter/Meteors/meteorBrown_big1.png"
meteor_brown_lg_02 = "space_shooter/Meteors/meteorBrown_big2.png"
meteor_brown_lg_03 = "space_shooter/Meteors/meteorBrown_big3.png"
meteor_brown_lg_04 = "space_shooter/Meteors/meteorBrown_big4.png"
meteor_brown_md_01 = "space_shooter/Meteors/meteorBrown_med1.png"
meteor_brown_md_02 = "space_shooter/Meteors/meteorBrown_med3.png"
meteor_brown_sm_01 = "space_shooter/Meteors/meteorBrown_small1.png"
meteor_brown_sm_02 = "space_shooter/Meteors/meteorBrown_small2.png"
meteor_brown_tn_01 = "space_shooter/Meteors/meteorBrown_tiny1.png"
meteor_brown_tn_02 = "space_shooter/Meteors/meteorBrown_tiny2.png"

[player.ship]
thrust_factor = 800.0
turn_factor = 40.0
velocity_damping = 0.8
rotation_rate_damping = 8.0
sprite_id = "player_ship_orange"
collision_radius = 75

[meteors.variants.brown.Large]
scale = 2.5
speed = 30
sprites = [
	"meteor_brown_lg_01",
	"meteor_brown_lg_02",
	"meteor_brown_lg_03",
	"meteor_brown_lg_04",
]
collision_radius = 32

[meteor.brown.Medium]
scale = 2.5
speed = 35
sprites = ["meteor_brown_md_01", "meteor_brown_md_02"]
collision_radius = 16

[meteor.brown.Small]
scale = 2.5
speed = 40
sprites = ["meteor_brown_sm_01", "meteor_brown_sm_02"]
collision_radius = 8

[meteor.brown.Tiny]
scale = 2.5
speed = 40
sprites = ["meteor_brown_tn_01", "meteor_brown_tn_02"]
collision_radius = 4

[viewport]
title = "Stroids"
resolution = [800, 600]
# Tells wasm to resize the window according to the available canvas
fit_canvas_to_parent = false
# Tells wasm not to override default event handling, like F5, Ctrl+R etc.
prevent_default_event_handling = false
background_color = "#111122"
camera_scale = 3.0
